language: python
python:
- '2.7'
- pypy
sudo: true
addons:
  apt:
    packages:
    - python-pip
install:
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- ansible-playbook -c local tests/test.yml -i tests/inventory --syntax-check
- ansible-playbook -c local tests/test.yml -i tests/inventory -e slack_token=$SLACK_TOKEN -e  slack_channel="devops-foundry"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
env:
  global:
  - secure: vIna4i1AndyOa4AUgu7qAnc7RWSHFc2hKK/tjd8OHkq3yMek64HZQqs6V1SxmgEO4vTLKh+XIOPBbJiLJx1INxiiluzD63bgaIQhsX0cUeQPhC75Ujfavt0Rs1p/z9DpQk4qijnKCUlzfADiJnq1qCYAgzxsOe+zwFPsIV8tlVWw8P0UeccSBCtNH5O6c0lGbO1H32eknqsVhESz5G7QigHzEkx8dLvA48Nk5yi7gNeZLzVdbGNx4f3EeLqpefoQken69vCueWmnGBk5vO+cdJnmg01GnGpmF+yhsUc+jjT3crJtgwIol7ai1vnA75ZSodJN9d5rOWqNDZ8D2x4w3H3OSjsd9dwNFczk6OMYHjF2z8vzYmxFxDMX4zKS0bLirBTfwKmSwgO5zebweqsrQyiOjG827+crw+4y1WW2PMfzJtnrVpvI3HSNYxw3yeaEXPJtnobvb5s6rqlGngjcwB0tDDD1xRrIwRXL3IjXiKVgWTEJgJzmabcIGllxrdbHnOuLGZWtGvNHKgiFnkW5lgYiSINUo3N4ysXqCAvL9VcjeH76THMkf+EPd3oBwPzGYHLY95spkFSboXl70kfgTOuORb/oJ577FmEJlY1/X+kQU4mUSDS41da6TNZNAIj0g46yMfLIQyrhteTL1Qmk3BSIFM6OXlPD6sDqwgdaEKs=
  - secure: SHA6PLQRPIl1vO485yN+X+7i6FJa4OhFv+0IoQQ1tMV4SslEy1W9tn+Kospf8S77z9Z/VYhNKrZmkwHFYngUFsv32duclU3PmsEi6CkJSPCErCfjlf8VHN7hPMYH48nNb06zM6djF+rdFRPYnTZ5tdRXaj4NWm4KHzSMe1QG8e7N6y5+jHWTsWl6Ddb4rt3s4BwASlQbzNPER67mgOr4t2aKjBhKjhV23jIZLueQrIeb+4CaZEErFasbb9snbQPIR9fVQ04fd/j1jiQQrVz71FGzJ4oUpgCukGWXuW+zoThTyGbPAhRqQq+KUocke+bcUQFKghWxi80aKPorpdSZoG1BWyeQ77mMOwv3rgZ33TuIoYkjMsKg8zmYYQsoEca7kUYQZbx1KUF4ClmdrANaE0W+5u/Kh31q9QV8Yx7ibe8RAnf7zvVAEoFHkiknx9+L7PjkqO5um+QFcMbP/NsrXRqH9X65QsMn79QBuuon0mfSMI9fMv23zj9czJL79fywGpw/FG54LcSyx4rJB/VuE/rutb2zvq2J+zCs3KuIg3q6+PfzkaK8Fysntts9jFm2wlXkDea3PIPEnvQgSerEHWm+HgZv7f6rKBuljG5SdOTAAc4vAd/jB2h3JDGWq9RXFUncioSFjRZgGqbueuCMoPGW4pfAlW/EiL5Y3+hf1DU=
