---
# UMD yum repository.
- name: debug vars
  debug:
    var: "{{ item }}"
  with_items:
    - umd_version
    - umd_repos[umd_version][ansible_distribution].ansible_distribution_major_version

- name: Add umd repository
  yum_repository:
    name: "{{ item.name }}"
    description: "UMD repo"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ umd_repos[umd_version][ansible_distribution].key }}"
    gpgcheck: yes
  with_items: "{{ umd_repos[umd_version][ansible_distribution][ansible_distribution_major_version] }}"

- name: Ensure prorities plugin is configured
  copy:
    src: etc/yum/pluginconf.d/priorities.conf
    dest: /etc/yum/pluginconf.d/prorities.conf
