---
- name: add the EGI APT key
  apt_key:
    url: http://repository.egi.eu/sw/production/umd/UMD-DEB-PGP-KEY
    state: present
  tags:
    - repos
    - apt

- name: get the deb
  get_url:
    url: 
    dest: /tmp/umd-release-3.0.0_all.deb

- name: add the release package
  apt:
    deb: /tmp/umd-release-3.0.0_all.deb
    state: present
    # update_cache: true
  tags:
    - repos
    - apt
