---
- debug:
    var: cmd
  tags:
    - debug

- debug:
    var: "{{ item }}"
  with_items:
    cmd.repos.Debian
  tags:
    - debug
- name: add the EGI APT key
  apt_key:
    url: http://repository.egi.eu/sw/production/umd/UMD-DEB-PGP-KEY
    state: present
  tags:
    - repos
    - apt

- name: Add repos
  apt_repository:
    repo: "deb {{ item.url }} {{ item.name }} main"
    state: present
  with_items: cmd.repos.Debian
  tags:
    - repos
    - apt
