---
- debug:
    var: "{{ item }}"
  with_items:
    "umd_repos[{{umd_release | default(3) }}]['Debian']['squeeze']"
  tags:
    - debug
- name: add the EGI APT key
  apt_key:
    url: http://repository.egi.eu/sw/production/umd/UMD-DEB-PGP-KEY
    state: present
  tags:
    - repos
    - apt

- name: Add repos
  apt_repository:
    repo: "deb {{ item.url }} {{ item.name }} main"
    state: present
  with_items: "{{umd_repos[umd_release | default(3)]['Debian']['squeeze']}}"
  tags:
    - repos
    - apt
